# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: R1
     type: GitHub
     endpoint: MyGithubConnection
     name: jainamanjain/Repo1
     version: c2d74536bd0d2267fd1f0c27a941f32e4415232f
     branch: master

jobs:
 - job: J2
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact1'
         ArtifactName: 'A1'
         publishLocation: 'Container'
      - powershell: |
            ls $(Build.ArtifactStagingDirectory)/