trigger: none

jobs:
 - job: J1
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact1.1'
         ArtifactName: 'A1.1'
 - job: J2
   pool:
    name: default
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact2'
         ArtifactName: 'A2'
