# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: R1
     type: GitHub
     endpoint: GitHubConnection1
     name: jainamanjain/Repo1

jobs:
 - job: J2
   pool:
    name: default
   steps:
      # - download: R1
      #   artifact: 'artifact3'
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact1'
         ArtifactName: 'A1'
         publishLocation: 'Container'
      - powershell: |
            ls $(Build.ArtifactStagingDirectory)/