# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



jobs:
 - job: J2
   pool:
    name: default
   steps:
     - task: PublishPipelineArtifact@0
       inputs:
         artifactName: 'A1'
         targetPath: 'artifact1'
