# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
 pipelines:
   - pipeline: Foobar
     source: Arsasana.Test2

jobs:
 - job: J1
   pool: 
    name : Default
   steps:
   - download: Foobar
     artifact: A1
     
 - deployment: D1
   pool: Default
   environment: 'E1Arsasana'
   strategy:
    runOnce:
      deploy: 
       steps:
         - download: Foobar




